name: paquexpress_agente_app
description: "Aplicación de Agente para Paquexpress S.A. de C.V."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1

  # HTTP y almacenamiento local
  http: ^1.2.1
  shared_preferences: ^2.2.2

  # Cámara y GPS
  camera: ^0.10.5+9
  geolocator: ^11.0.0

  # Mapas tipo OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # utilidades
  path_provider: ^2.1.2
  url_launcher: ^6.3.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/map_placeholder.png
